# Generated by Django 2.0.4 on 2018-11-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
