# Generated by Django 2.0.4 on 2018-11-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0002_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
    ]
