# Generated by Django 2.0.4 on 2018-11-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0003_remove_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
    ]
