# Generated by Django 2.0.4 on 2018-11-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0007_auto_20181106_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 11, 6, 5, 59, 55, 595353)),
        ),
    ]
