# Generated by Django 2.0.4 on 2018-11-06 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0008_auto_20181106_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 11, 6, 6, 0, 2, 539682)),
        ),
    ]
