# Generated by Django 2.0.4 on 2018-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0010_auto_20181106_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=11925263463),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
