# Generated by Django 2.0.4 on 2018-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0011_auto_20181106_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=11088692821),
        ),
    ]
