# Generated by Django 2.0.4 on 2018-11-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createaccount', '0013_auto_20181112_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=11301943896),
        ),
    ]
